version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: medbook-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medbook}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - medbook_pgdata:/var/lib/postgresql/data

volumes:
  medbook_pgdata:
    external: true
