# Generated by Django 5.1.15 on 2026-05-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["user__last_name", "user__first_name"],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
    ]
