# Generated by Django 5.1.15 on 2026-05-23 06:08

from django.db import migrations


SPECIALTIES = [
    {"name": "Cardiology", "slug": "cardiology"},
    {"name": "Dermatology", "slug": "dermatology"},
    {"name": "General Practice", "slug": "general-practice"},
    {"name": "Neurology", "slug": "neurology"},
    {"name": "Pediatrics", "slug": "pediatrics"},
]


def create_specialties(apps, schema_editor):
    """Create the 5 initial medical specialties."""
    Specialty = apps.get_model("doctors", "Specialty")
    Specialty.objects.bulk_create(
        [Specialty(**data) for data in SPECIALTIES],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_alter_schedule_day_of_week_and_more"),
    ]

    operations = [
        migrations.RunPython(create_specialties, reverse_code=migrations.RunPython.noop),
    ]
